updates from build run through:
gnidan/eth-dev pull request #6
Opened 2017-02-27 09:33 UTC by chatch

- seems the path to parity has changed to /parity/parity although the Dockerfile on dockerhub does not reflect this
- example dapp updated to latest truffle 3 as it failed to compile

2017-02-27 14:08 UTC, gnidan requested changes
Looks good apart from the one change. I will try out the changes when I get home from work later

2017-02-27 14:08 UTC, gnidan commented on dapps/example/truffle.js
> -          host: "parity-ropsten",
Mind leaving the ropsten network config here? To show how truffle apps can make use of that parity container

2017-02-28 03:06 UTC, chatch commented on dapps/example/truffle.js
> -          host: "parity-ropsten",
sure. I must of have blown that away when i copied in all the latest "truffle init" app source.

2017-02-28 03:07 UTC, chatch commented
ropsten in truffle.js restored

2017-02-28 03:18 UTC, gnidan approved these changes

2017-02-28 08:13 UTC, merged